[workspace]
resolver = "3"
members = ["prototyper", "bench-kernel", "test-kernel", "xtask"]

[workspace.package]
edition = "2024"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/prototyper"

[profile.release]
debug = true
